# permissions for end users to edit sentinels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: sentinel-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sentinel-operator
    app.kubernetes.io/part-of: sentinel-operator
    app.kubernetes.io/managed-by: kustomize
  name: sentinel-editor-role
rules:
- apiGroups:
  - trafficflow.skoala.daocloud.io
  resources:
  - sentinels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - trafficflow.skoala.daocloud.io
  resources:
  - sentinels/status
  verbs:
  - get
